<?= $this->doctype() ?>

<html lang="it">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="" content="" />
    <link rel="icon" href="favicon.ico" />
    <?= $this->headMeta()
             ->appendName('viewport', 'width=device-width, initial-scale=1.0')
             ->appendName('Pragma', 'no-cache')
             ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
             ->appendHttpEquiv('Cache-control', 'no-cache')
             ->appendHttpEquiv('Expires', '0')
    ?>
        
    <?= $this->headTitle('Tic-tac-toe game')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'])
             //->appendStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css')
             //->appendStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css')
             
             ->appendStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css')
             ->appendStylesheet('https://use.fontawesome.com/releases/v5.7.0/css/all.css')
             ->appendStylesheet('https://fonts.googleapis.com/css?family=Stylish&display=swap')
    
             ->appendStylesheet('/css/main.css');
    
    ?>
    
    <?= $this->headScript()
             //->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js')
             //->appendFile($this->basePath('js/general.js'))
             //->appendFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js')
             ->appendFile('https://code.jquery.com/jquery-3.2.1.min.js')
             ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js')
             ->appendFile('https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js')
             ->appendFile('https://www.gstatic.com/charts/loader.js');
    ?>    

    <?= $this->head;?>
</head>
<body>
	<div class="container">	
		<?= $this->content ?>
        
    	<?= $this->inlineScript() ?>
    </div>
</body>
</html>